services:
  php:
    build: ./PHP
    ports:
      - "8081:80" #-> external 8080, internal 80
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql

  mysql:
    build: ./MySQL
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: